# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coeffupdate <- function(coeffs, S, SJ, SS, taustar, sigsquared, beta, nrow, ncol) {
    .Call(`_cpop_coeffupdate`, coeffs, S, SJ, SS, taustar, sigsquared, beta, nrow, ncol)
}

prune <- function(x, nrows) {
    .Call(`_cpop_prune`, x, nrows)
}

