# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prune <- function(x, nrows) {
    .Call('_cpop_prune', PACKAGE = 'cpop', x, nrows)
}

coeffs_update_cpp <- function(SXY, SX2, S, SS, Xs, SX, SP, Seglen, taustar, Sstar, Xt) {
    .Call('_cpop_coeffs_update_cpp', PACKAGE = 'cpop', SXY, SX2, S, SS, Xs, SX, SP, Seglen, taustar, Sstar, Xt)
}

